const STRIPE_PK='VOTRE_CLE_PUBLIQUE_STRIPE';
const STRIPE_PRICES={pro:'VOTRE_ID_PRO',biz:'VOTRE_ID_BIZ',ent:'VOTRE_ID_ENT'};
let stripeInstance=null,selectedPlan='pro';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
const FREE_LIMIT=3,CYCLE_MS=48*3600*1000;
let currentUser=null,currentTool='pdf-to-text',uploadedFiles=[],conversionResult=null;

const TOOLS={
  'pdf-to-text':{t:'PDF vers Texte',d:'Extraire le texte',i:'fa-file-alt',c:'#2B7BF5',bg:'rgba(43,123,245,.1)',ac:'.pdf',m:false,tx:false,pro:false,oi:'fa-file-alt',ol:'TXT',cat:'convert'},
  'image-to-pdf':{t:'Image vers PDF',d:'Images en document',i:'fa-file-image',c:'#10B981',bg:'rgba(16,185,129,.1)',ac:'.jpg,.jpeg,.png',m:true,tx:false,pro:false,oi:'fa-file-pdf',ol:'PDF',cat:'convert'},
  'text-to-pdf':{t:'Texte vers PDF',d:'Texte en document',i:'fa-pen-nib',c:'#F59E0B',bg:'rgba(245,158,11,.1)',ac:null,m:false,tx:true,pro:false,oi:'fa-file-pdf',ol:'PDF',cat:'convert'},
  'pdf-to-image':{t:'PDF vers Image',d:'Pages en images PNG',i:'fa-image',c:'#0EA5E9',bg:'rgba(14,165,233,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-image',ol:'PNG',cat:'convert'},
  'pdf-to-word':{t:'PDF vers Word',d:'Export Word',i:'fa-file-word',c:'#2563EB',bg:'rgba(37,99,235,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-word',ol:'DOC',cat:'convert'},
  'pdf-to-excel':{t:'PDF vers Excel',d:'Donnees en tableur',i:'fa-file-excel',c:'#16A34A',bg:'rgba(22,163,74,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-excel',ol:'CSV',cat:'convert'},
  'pdf-to-pptx':{t:'PDF vers PowerPoint',d:'Export presentation',i:'fa-file-powerpoint',c:'#EA580C',bg:'rgba(234,88,12,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-powerpoint',ol:'PPTX',cat:'convert'},
  'pdf-to-markdown':{t:'PDF vers Markdown',d:'Texte en Markdown',i:'fa-brands fa-markdown',c:'#8B5CF6',bg:'rgba(139,92,246,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-brands fa-markdown',ol:'MD',cat:'convert'},
  'markdown-to-pdf':{t:'Markdown vers PDF',d:'Markdown en document',i:'fa-file-code',c:'#6366F1',bg:'rgba(99,102,241,.1)',ac:null,m:false,tx:true,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'convert'},
  'csv-to-pdf':{t:'CSV vers PDF',d:'Tableau en document',i:'fa-table',c:'#14B8A6',bg:'rgba(20,184,166,.1)',ac:null,m:false,tx:true,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'convert'},
  'merge-pdf':{t:'Fusionner PDF',d:'Combiner des PDF',i:'fa-layer-group',c:'#EF4444',bg:'rgba(239,68,68,.1)',ac:'.pdf',m:true,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'organize'},
  'split-pdf':{t:'Diviser PDF',d:'Extraire des pages',i:'fa-cut',c:'#E11D48',bg:'rgba(225,29,72,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'organize'},
  'rotate-pdf':{t:'Pivoter PDF',d:'Tourner les pages',i:'fa-redo',c:'#0891B2',bg:'rgba(8,145,178,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'organize'},
  'number-pages':{t:'Numeroter PDF',d:'Numeros de page',i:'fa-list-ol',c:'#6D28D9',bg:'rgba(109,40,217,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'organize'},
  'html-to-pdf':{t:'HTML vers PDF',d:'Code HTML en document',i:'fa-code',c:'#7C3AED',bg:'rgba(124,58,237,.1)',ac:null,m:false,tx:true,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'optimize'},
  'watermark-pdf':{t:'Filigrane PDF',d:'Ajouter un filigrane',i:'fa-stamp',c:'#CA8A04',bg:'rgba(202,138,4,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'optimize'},
  'extract-images':{t:'Extraire images',d:'Images du PDF',i:'fa-images',c:'#DB2777',bg:'rgba(219,39,119,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-image',ol:'IMG',cat:'optimize'},
  'compress-pdf':{t:'Compresser PDF',d:'Reduire la taille',i:'fa-compress-alt',c:'#64748B',bg:'rgba(100,116,139,.1)',ac:'.pdf',m:false,tx:false,pro:true,oi:'fa-file-pdf',ol:'PDF',cat:'optimize'}
};

function getUsers(){return JSON.parse(localStorage.getItem('pdfshift_users')||'{}')}
function saveUsers(u){localStorage.setItem('pdfshift_users',JSON.stringify(u))}
function getUser(){const id=localStorage.getItem('pdfshift_session');return id?getUsers()[id]||null:null}
function saveUser(u){const us=getUsers();us[u.id]=u;saveUsers(us);currentUser=u}
function refreshCycle(u){const n=Date.now();if(!u.cycleStart){u.cycleStart=n;u.cycleUsed=0;saveUser(u);return}if(n-u.cycleStart>=CYCLE_MS){u.cycleStart=n;u.cycleUsed=0;saveUser(u)}}
function getRemaining(u){if(u.isPro)return Infinity;refreshCycle(u);return Math.max(0,FREE_LIMIT-(u.cycleUsed||0))}
function consume(u){if(u.isPro){u.totalConversions=(u.totalConversions||0)+1;saveUser(u);return true}if(getRemaining(u)<=0)return false;u.cycleUsed=(u.cycleUsed||0)+1;u.totalConversions=(u.totalConversions||0)+1;saveUser(u);return true}
function getTimeLeft(u){refreshCycle(u);return Math.max(0,CYCLE_MS-(Date.now()-u.cycleStart))}
function fmtTime(ms){const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h>0?h+'h '+String(m).padStart(2,'0')+'min':m+'min '+String(sec).padStart(2,'0')+'s'}
function fmtSize(b){return b<1024?b+' o':b<1048576?(b/1024).toFixed(1)+' Ko':(b/1048576).toFixed(2)+' Mo'}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}

function typewriter(el,txt,speed=45){let i=0;el.textContent='';function type(){if(i<txt.length){el.textContent+=txt.charAt(i);i++;setTimeout(type,speed)}else el.style.borderRight='none'}type()}

function initReveal(){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')})},{threshold:.08,rootMargin:'0px 0px -30px 0px'});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el))}

function initCounters(){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&!e.target.dataset.done){e.target.dataset.done='1';const t=+e.target.dataset.target;let s=null;function step(ts){if(!s)s=ts;const p=Math.min((ts-s)/1800,1);e.target.textContent=Math.round((1-Math.pow(1-p,3))*t).toLocaleString('fr-FR');if(p<1)requestAnimationFrame(step)}requestAnimationFrame(step)}})},{threshold:.5});document.querySelectorAll('.counter').forEach(el=>obs.observe(el))}

function navigate(page){
  if(page==='dashboard'&&!getUser()){openModal('login');toast('Connectez-vous','info');return}
  const cur=document.querySelector('.page-visible'),next=document.getElementById('page-'+page);
  if(!next||cur===next)return;
  cur.style.opacity='0';cur.style.transform='translateY(8px)';
  setTimeout(()=>{cur.classList.replace('page-visible','page-hidden');cur.style.opacity='';cur.style.transform='';
    next.classList.replace('page-hidden','page-visible');next.style.opacity='0';next.style.transform='translateY(8px)';
    requestAnimationFrame(()=>{next.style.opacity='1';next.style.transform='translateY(0)'});},180);
  document.querySelectorAll('.nav-link[data-page]').forEach(l=>l.classList.remove('active'));
  document.querySelector(`.nav-link[data-page="${page}"]`)?.classList.add('active');
  closeDropdown();window.scrollTo({top:0,behavior:'smooth'});
  if(page==='dashboard')refreshDashboard();if(page==='pricing')buildPricing();
  setTimeout(initReveal,100);
}
function toggleDropdown(){document.getElementById('dropdownMenu').classList.toggle('open')}
function closeDropdown(){document.getElementById('dropdownMenu').classList.remove('open')}
document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown'))closeDropdown()});

function toast(msg,type='info'){
  const c=document.getElementById('toastContainer'),icons={success:'fa-check-circle',error:'fa-exclamation-circle',warning:'fa-exclamation-triangle',info:'fa-info-circle'};
  const t=document.createElement('div');t.className='toast toast-'+type;t.innerHTML='<i class="fas '+icons[type]+'"></i> '+msg;
  c.appendChild(t);setTimeout(()=>{t.style.opacity='0';t.style.transform='translateY(-8px)';t.style.transition='all .3s';setTimeout(()=>t.remove(),300)},4000);
}

function openModal(id){document.getElementById('modalOverlay').style.display='flex';document.querySelectorAll('.modal').forEach(m=>m.style.display='none');document.getElementById('modal-'+id).style.display='block';document.body.style.overflow='hidden'}
function closeModal(){document.getElementById('modalOverlay').style.display='none';document.body.style.overflow=''}
function switchModal(id){document.querySelectorAll('.modal').forEach(m=>m.style.display='none');document.getElementById('modal-'+id).style.display='block'}

function handleRegister(e){
  e.preventDefault();const name=document.getElementById('regName').value.trim(),email=document.getElementById('regEmail').value.trim().toLowerCase(),pw=document.getElementById('regPassword').value,pw2=document.getElementById('regPasswordConfirm').value;
  if(pw!==pw2){toast('Mots de passe differents','error');return}
  const users=getUsers();if(Object.values(users).find(u=>u.email===email)){toast('E-mail deja utilise','error');return}
  const user={id:'u_'+Date.now(),name,email,password:btoa(pw),isPro:false,cycleStart:Date.now(),cycleUsed:0,totalConversions:0,history:[],createdAt:Date.now()};
  users[user.id]=user;saveUsers(users);localStorage.setItem('pdfshift_session',user.id);
  currentUser=user;closeModal();updateNav();toast('Bienvenue '+name+' !','success');
}
function handleLogin(e){
  e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase(),pw=document.getElementById('loginPassword').value;
  const user=Object.values(getUsers()).find(u=>u.email===email);
  if(!user||atob(user.password)!==pw){toast('Identifiants incorrects','error');return}
  localStorage.setItem('pdfshift_session',user.id);currentUser=user;closeModal();updateNav();toast('Bon retour, '+user.name+' !','success');
}
function socialLogin(p){const e='user_'+p+'@exemple.com';let u=Object.values(getUsers()).find(x=>x.email===e);if(!u){u={id:'u_'+Date.now(),name:p.charAt(0).toUpperCase()+p.slice(1)+' User',email:e,password:btoa('social'),isPro:false,cycleStart:Date.now(),cycleUsed:0,totalConversions:0,history:[],createdAt:Date.now()};const us=getUsers();us[u.id]=u;saveUsers(us)}localStorage.setItem('pdfshift_session',u.id);currentUser=u;closeModal();updateNav();toast('Connecte avec '+p,'success')}
function logout(){localStorage.removeItem('pdfshift_session');currentUser=null;updateNav();navigate('home');toast('Deconnecte','info')}
function togglePassword(id,btn){const inp=document.getElementById(id),ic=btn.querySelector('i');inp.type=inp.type==='password'?'text':'password';ic.className=inp.type==='text'?'fas fa-eye-slash':'fas fa-eye'}
function checkPasswordStrength(pw){const bars=document.querySelectorAll('#strengthBars>div'),txt=document.getElementById('strengthText');let s=0;if(pw.length>=6)s++;if(pw.length>=10)s++;if(/[A-Z]/.test(pw)&&/[a-z]/.test(pw))s++;if(/[0-9]/.test(pw)&&/[^A-Za-z0-9]/.test(pw))s++;const c=['rgba(255,255,255,.05)','#EF4444','#F59E0B','#2B7BF5','#10B981'],l=['','Faible','Moyen','Bon','Excellent'];bars.forEach((b,i)=>b.style.background=i<s?c[s]:c[0]);txt.textContent=pw.length>0?l[s]:'';txt.style.color=c[s]}

function updateNav(){
  const u=getUser(),auth=document.getElementById('navAuth'),dash=document.getElementById('navDashboard');
  if(u){dash.style.display='inline-flex';auth.innerHTML=`<div style="display:flex;align-items:center;gap:8px"><div style="width:28px;height:28px;background:var(--blue-g);border:1px solid rgba(43,123,245,.15);border-radius:6px;display:flex;align-items:center;justify-content:center"><i class="fas fa-user" style="color:var(--blue);font-size:10px"></i></div><span style="font-size:12px;font-weight:500;color:var(--fg2)">${u.name}</span>${u.isPro?'<span style="background:var(--blue-g);color:var(--blue);font-size:9px;font-weight:700;padding:2px 6px;border-radius:4px;border:1px solid rgba(43,123,245,.15)">PRO</span>':''}</div><button class="btn-ghost" onclick="logout()" style="color:rgba(255,255,255,.4)"><i class="fas fa-sign-out-alt"></i></button>`}
  else{dash.style.display='none';auth.innerHTML='<button class="btn-ghost" onclick="openModal(\'login\')">Se connecter</button><button class="btn-nav-cta" onclick="openModal(\'register\')">Essai gratuit</button>'}
}

function buildDropdown(){const m=document.getElementById('dropdownMenu');const cats={convert:{name:'Convertir',icon:'fa-exchange-alt'},organize:{name:'Organiser',icon:'fa-folder-open'},optimize:{name:'Optimiser',icon:'fa-magic'}};let h='';for(const[cid,cat]of Object.entries(cats)){h+=`<div class="dm-col"><p class="dm-title"><i class="fas ${cat.icon}" style="margin-right:4px"></i>${cat.name}</p>`;for(const[id,t]of Object.entries(TOOLS)){if(t.cat===cid)h+=`<a onclick="selectTool('${id}')"><i class="fas ${t.i}"></i>${t.t}${t.pro?' <i class="fas fa-lock" style="font-size:9px;color:var(--purple)"></i>':''}</a>`}h+='</div>'}m.innerHTML=h}

function buildToolsGrid(){const g=document.getElementById('toolsGrid');g.innerHTML='';let i=0;for(const[id,t]of Object.entries(TOOLS)){const c=document.createElement('div');c.className='tool-card reveal';c.style.transitionDelay=(i*0.03)+'s';c.onclick=()=>selectTool(id);c.innerHTML=`<div class="tc-icon" style="background:${t.bg};color:${t.c};border:1px solid ${t.c}15"><i class="fas ${t.i}"></i></div><div class="tc-name">${t.t}</div><div class="tc-desc">${t.d}</div>${t.pro?'<div class="tc-lock"><i class="fas fa-lock"></i> Pro</div>':''}`;g.appendChild(c);i++}setTimeout(initReveal,50)}

function buildVisBand(){const t=document.getElementById('vbTrack');const items=[{s:'pdf1',l:'Convertir'},{s:'pdf2',l:'Compresser'},{s:'pdf3',l:'Fusionner'},{s:'pdf4',l:'Modifier'},{s:'pdf5',l:'Signer'},{s:'pdf6',l:'Proteger'}];let h='';for(let j=0;j<2;j++)items.forEach(it=>{h+=`<div class="vb-item"><img src="https://picsum.photos/seed/${it.s}/240/120" alt="${it.l}"><p>${it.l}</p></div>`});t.innerHTML=h}

function selectTool(id){
  const t=TOOLS[id];if(t.pro){const u=getUser();if(!u){openModal('login');toast('Connectez-vous','warning');return}if(!u.isPro){openModal('pro-lock');return}}
  currentTool=id;document.getElementById('toolTitle').textContent=t.t;document.getElementById('toolDesc').textContent=t.d;
  const ic=document.getElementById('toolIcon');ic.innerHTML=`<i class="fas ${t.i}"></i>`;ic.style.background=t.bg;ic.style.color=t.c;ic.style.borderColor=t.c+'15';
  document.getElementById('toolProBadge').style.display=t.pro?'inline-flex':'none';
  const fi=document.getElementById('fileInput');if(t.ac){fi.accept=t.ac;fi.multiple=t.m;document.getElementById('acceptedFormats').textContent=t.ac.toUpperCase().replace(/\./g,'').replace(/,/g,', ');document.getElementById('dropZone').style.display='block'}else document.getElementById('dropZone').style.display='none';
  document.getElementById('textInputArea').style.display=t.tx?'block':'none';document.getElementById('textInput').value='';
  document.getElementById('pageRangeArea').style.display=id==='split-pdf'?'block':'none';document.getElementById('watermarkArea').style.display=id==='watermark-pdf'?'block':'none';
  uploadedFiles=[];conversionResult=null;resetToolUI();updateLimitUI();navigate('tools');
}
function resetToolUI(){document.getElementById('dropContent').style.display='block';document.getElementById('filePreview').style.display='none';document.getElementById('convertBtn').disabled=true;document.getElementById('resultArea').style.display='none';document.getElementById('textResult').style.display='none'}
function clearFile(){uploadedFiles=[];document.getElementById('fileInput').value='';resetToolUI()}
function updateLimitUI(){const u=getUser(),b=document.getElementById('limitBanner');if(u&&u.isPro){b.style.display='none';return}b.style.display='flex';const rem=u?getRemaining(u):FREE_LIMIT;document.getElementById('limitText').textContent=rem+' restante'+(rem!==1?'s':'');const f=document.getElementById('limitProgress');f.style.width=(rem/FREE_LIMIT*100)+'%';f.style.background=rem===0?'#EF4444':'#F59E0B'}

const dropZone=document.getElementById('dropZone'),fileInput=document.getElementById('fileInput');
dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.classList.add('drag-over')});
dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('drag-over'));
dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('drag-over');handleFiles(e.dataTransfer.files)});
fileInput.addEventListener('change',e=>handleFiles(e.target.files));
function handleFiles(files){if(!files||!files.length)return;const u=getUser();if(!u){toast('Connectez-vous','warning');openModal('login');return}const t=TOOLS[currentTool];uploadedFiles=Array.from(files);for(const f of uploadedFiles){const ext='.'+f.name.split('.').pop().toLowerCase();if(t.ac&&!t.ac.includes(ext)){toast('Format non supporte','error');uploadedFiles=[];return}const mx=u.isPro?52428800:5242880;if(f.size>mx){toast('Max '+(u.isPro?'50':'5')+' Mo','error');uploadedFiles=[];return}}document.getElementById('dropContent').style.display='none';const prev=document.getElementById('filePreview');prev.style.display='flex';prev.querySelector('i').className='fas fa-file-pdf';document.getElementById('fileName').textContent=uploadedFiles.length===1?uploadedFiles[0].name:uploadedFiles.length+' fichiers';document.getElementById('fileSize').textContent=uploadedFiles.length===1?fmtSize(uploadedFiles[0].size):uploadedFiles.map(f=>fmtSize(f.size)).join(', ');document.getElementById('convertBtn').disabled=false;updateLimitUI()}

function showOverlay(iI,iL,oI,oL){document.getElementById('cvFmtIn').innerHTML=`<i class="fas ${iI}"></i><span>${iL}</span>`;document.getElementById('cvFmtOut').innerHTML=`<i class="fas ${oI}"></i><span>${oL}</span>`;['cvFmtIn','cvFmtOut'].forEach(id=>document.getElementById(id).classList.remove('done'));document.getElementById('cvArrowWrap').classList.remove('active');document.getElementById('cvRingCircle').style.strokeDashoffset='553';document.getElementById('cvRingCircle').style.stroke='#2B7BF5';document.getElementById('cvRingInner').classList.remove('done');document.getElementById('cvSpinIcon').style.display='block';document.getElementById('cvCheckIcon').style.display='none';document.getElementById('cvPercentText').textContent='0%';const c=document.getElementById('cvParticles');c.innerHTML='';for(let i=0;i<14;i++){const p=document.createElement('div');p.className='cv-particle';const a=Math.random()*Math.PI*2,d=70+Math.random()*120;p.style.cssText=`left:${50+Math.cos(a)*d}%;top:${50+Math.sin(a)*d}%;width:${2+Math.random()*3}px;height:${2+Math.random()*3}px;animation-delay:${Math.random()*2}s;animation-duration:${2+Math.random()*2}s`;c.appendChild(p)}document.getElementById('cvOverlay').classList.add('active');document.body.style.overflow='hidden'}
function updateOverlay(pct,step){document.getElementById('cvRingCircle').style.strokeDashoffset=553-553*pct/100;document.getElementById('cvPercentText').textContent=Math.round(pct)+'%';document.getElementById('cvStepText').textContent=step;if(pct>15)document.getElementById('cvArrowWrap').classList.add('active');if(pct>40)document.getElementById('cvFmtIn').classList.add('done');if(pct>85)document.getElementById('cvFmtOut').classList.add('done')}
function completeOverlay(){document.getElementById('cvRingCircle').style.stroke='#10B981';document.getElementById('cvRingCircle').style.strokeDashoffset='0';document.getElementById('cvRingInner').classList.add('done');document.getElementById('cvSpinIcon').style.display='none';document.getElementById('cvCheckIcon').style.display='block';document.getElementById('cvStepText').textContent='Termine !';document.getElementById('cvPercentText').textContent='100%'}
function hideOverlay(){document.getElementById('cvOverlay').classList.remove('active');document.body.style.overflow=''}

async function startConversion(){
  const u=getUser();if(!u){openModal('login');return}const t=TOOLS[currentTool];
  if(!t.tx&&!uploadedFiles.length){toast('Selectionnez un fichier','warning');return}
  if(t.tx&&!document.getElementById('textInput').value.trim()){toast('Saisissez du texte','warning');return}
  if(!consume(u)){toast('Limite atteinte ! '+fmtTime(getTimeLeft(u)),'error');updateLimitUI();return}
  document.getElementById('convertBtn').disabled=true;document.getElementById('resultArea').style.display='none';
  showOverlay('fa-file-pdf','PDF',t.oi,t.ol);
  try{let result;const steps=[{p:10,t:'Lecture...'},{p:30,t:'Analyse...'},{p:55,t:'Traitement...'},{p:75,t:'Conversion...'},{p:92,t:'Finalisation...'}];
    switch(currentTool){case'pdf-to-text':result=await cvPdfToText(steps);break;case'image-to-pdf':result=await cvImageToPdf(steps);break;case'text-to-pdf':result=await cvTextToPdf(steps);break;case'pdf-to-image':result=await cvPdfToImage(steps);break;case'pdf-to-word':result=await cvPdfToWord(steps);break;case'pdf-to-excel':result=await cvPdfToExcel(steps);break;case'pdf-to-pptx':result=await cvPdfToPptx(steps);break;case'pdf-to-markdown':result=await cvPdfToMd(steps);break;case'markdown-to-pdf':result=await cvMdToPdf(steps);break;case'csv-to-pdf':result=await cvCsvToPdf(steps);break;case'merge-pdf':result=await cvMergePdf(steps);break;case'split-pdf':result=await cvSplitPdf(steps);break;case'rotate-pdf':result=await cvRotatePdf(steps);break;case'number-pages':result=await cvNumberPages(steps);break;case'html-to-pdf':result=await cvHtmlToPdf(steps);break;case'watermark-pdf':result=await cvWatermarkPdf(steps);break;case'extract-images':result=await cvExtractImages(steps);break;case'compress-pdf':result=await cvCompressPdf(steps);break}
    completeOverlay();await delay(1200);hideOverlay();conversionResult=result;
    u.history.unshift({id:Date.now(),tool:currentTool,fileName:result.fileName,date:Date.now()});if(u.history.length>50)u.history=u.history.slice(0,50);saveUser(u);showResult(result);
  }catch(err){console.error(err);hideOverlay();toast('Erreur : '+err.message,'error');document.getElementById('convertBtn').disabled=false}
  updateLimitUI();
}
function animSteps(steps,base=300){return(async()=>{for(const s of steps){updateOverlay(s.p,s.t);await delay(base+Math.random()*120)}})()}
function readAsUrl(f){return new Promise((r,j)=>{const re=new FileReader();re.onload=()=>r(re.result);re.onerror=j;re.readAsDataURL(f)})}
function loadImg(src){return new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src:src})}
function renderPage(page,scale=1.5){const vp=page.getViewport({scale});const c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;return page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise.then(()=>({canvas:c,w:vp.width,h:vp.height}))}
function parsePages(s){const p=new Set();s.split(',').forEach(part=>{part=part.trim();if(part.includes('-')){const[a,b]=part.split('-').map(Number);for(let i=a;i<=b;i++)p.add(i)}else{const n=parseInt(part);if(!isNaN(n))p.add(n)}});return Array.from(p).sort((a,b)=>a-b)}
function simpleMdToHtml(md){return md.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/^- (.+)$/gm,'<li>$1</li>').replace(/\n\n/g,'<br><br>').replace(/\n/g,'<br>')}

async function cvPdfToText(s){animSteps(s,450);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;let txt='';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const c=await pg.getTextContent();txt+=c.items.map(it=>it.str).join(' ')+'\n\n';updateOverlay(10+80*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'text',text:txt,fileName:uploadedFiles[0].name.replace('.pdf','')+'.txt',info:pdf.numPages+' page(s)'}}
async function cvImageToPdf(s){const{jsPDF}=window.jspdf;animSteps(s,250);const doc=new jsPDF();for(let i=0;i<uploadedFiles.length;i++){if(i>0)doc.addPage();const url=await readAsUrl(uploadedFiles[i]);const img=await loadImg(url);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/img.width,ph/img.height,1);doc.addImage(url,'JPEG',(pw-img.width*r)/2,(ph-img.height*r)/2,img.width*r,img.height*r);updateOverlay(20+70*i/uploadedFiles.length,'Image '+(i+1));await delay(70)}return{type:'blob',blob:doc.output('blob'),fileName:'images.pdf',info:uploadedFiles.length+' image(s)'}}
async function cvTextToPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const txt=document.getElementById('textInput').value;const doc=new jsPDF();doc.setFont('helvetica');doc.setFontSize(12);const lines=doc.splitTextToSize(txt,170);const ph=doc.internal.pageSize.getHeight()-40;let y=20,i=0;while(i<lines.length){if(y+7>ph+20){doc.addPage();y=20}doc.text(lines[i],20,y);y+=7;i++}return{type:'blob',blob:doc.output('blob'),fileName:'texte.pdf',info:lines.length+' ligne(s)'}}
async function cvPdfToImage(s){animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const imgs=[];for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const{canvas}=await renderPage(pg,2);imgs.push(canvas.toDataURL('image/png'));updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(90)}return{type:'images',images:imgs,fileName:uploadedFiles[0].name.replace('.pdf',''),info:imgs.length+' image(s)'}}
async function cvPdfToWord(s){animSteps(s,400);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;let html='<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><style>body{font-family:Calibri,sans-serif;font-size:12pt}p{margin:0 0 8px}</style></head><body>';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const c=await pg.getTextContent();html+='<p style="page-break-after:always"><b>--- Page '+i+' ---</b></p>';c.items.forEach(it=>html+='<p>'+it.str+'</p>');updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}html+='</body></html>';return{type:'blob',blob:new Blob([html],{type:'application/msword'}),fileName:uploadedFiles[0].name.replace('.pdf','')+'.doc',info:pdf.numPages+' page(s)'}}
async function cvPdfToExcel(s){animSteps(s,400);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;let csv='';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const c=await pg.getTextContent();let lastY=null;c.items.forEach(it=>{const y=Math.round(it.transform[5]);if(lastY!==null&&Math.abs(y-lastY)>5)csv+='\n';else if(lastY!==null)csv+=',';csv+='"'+it.str.replace(/"/g,'""')+'"';lastY=y});csv+='\n\n';updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'blob',blob:new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}),fileName:uploadedFiles[0].name.replace('.pdf','')+'.csv',info:pdf.numPages+' page(s)'}}
async function cvPdfToPptx(s){const{jsPDF}=window.jspdf;animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF({orientation:'landscape'});for(let i=1;i<=pdf.numPages;i++){if(i>0)doc.addPage();const pg=await pdf.getPage(i);const{canvas,w,h}=await renderPage(pg,1.2);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/w,ph/h);doc.addImage(canvas.toDataURL('image/jpeg',.85),'JPEG',(pw-w*r)/2,(ph-h*r)/2,w*r,h*r);updateOverlay(10+85*i/pdf.numPages,'Slide '+i);await delay(70)}return{type:'blob',blob:doc.output('blob'),fileName:uploadedFiles[0].name.replace('.pdf','')+'.pptx',info:pdf.numPages+' slide(s)'}}
async function cvPdfToMd(s){animSteps(s,400);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;let md='# Document\n\n';for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const c=await pg.getTextContent();md+='## Page '+i+'\n\n'+c.items.map(it=>it.str).join(' ')+'\n\n---\n\n';updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'text',text:md,fileName:uploadedFiles[0].name.replace('.pdf','')+'.md',info:pdf.numPages+' page(s)'}}
async function cvMdToPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const md=document.getElementById('textInput').value;const html=simpleMdToHtml(md);const doc=new jsPDF();doc.setFont('helvetica');doc.setFontSize(11);const txt=html.replace(/<[^>]+>/g,'');const lines=doc.splitTextToSize(txt,170);const ph=doc.internal.pageSize.getHeight()-40;let y=20,i=0;while(i<lines.length){if(y+6>ph+20){doc.addPage();y=20}doc.text(lines[i],20,y);y+=6;i++}return{type:'blob',blob:doc.output('blob'),fileName:'markdown.pdf',info:lines.length+' ligne(s)'}}
async function cvCsvToPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const csv=document.getElementById('textInput').value;const rows=csv.split('\n').filter(r=>r.trim());const doc=new jsPDF({orientation:'landscape'});doc.setFont('helvetica');doc.setFontSize(9);let y=15;rows.forEach((row)=>{const cols=row.split(',');if(y+8>doc.internal.pageSize.getHeight()-10){doc.addPage();y=15}const colW=(doc.internal.pageSize.getWidth()-20)/Math.max(cols.length,1);cols.forEach((col,ci)=>{doc.text(col.trim().replace(/^"|"$/g,''),10+ci*colW,y,{maxWidth:colW-4})});y+=8});return{type:'blob',blob:doc.output('blob'),fileName:'csv.pdf',info:rows.length+' ligne(s)'}}
async function cvMergePdf(s){const{jsPDF}=window.jspdf;animSteps(s,250);const all=[];for(const f of uploadedFiles){const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;for(let p=1;p<=pdf.numPages;p++){const pg=await pdf.getPage(p);const{canvas,w,h}=await renderPage(pg,1.5);all.push({img:canvas.toDataURL('image/jpeg',.9),w,h})}}updateOverlay(60,'Fusion...');await delay(200);const doc=new jsPDF();all.forEach((pg,idx)=>{if(idx>0)doc.addPage();const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/pg.w,ph/pg.h);doc.addImage(pg.img,'JPEG',(pw-pg.w*r)/2,(ph-pg.h*r)/2,pg.w*r,pg.h*r)});return{type:'blob',blob:doc.output('blob'),fileName:'fusionne.pdf',info:all.length+' page(s)'}}
async function cvSplitPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const pages=parsePages(document.getElementById('pageRangeInput').value||'1');const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF();let added=false;for(const p of pages){if(p<1||p>pdf.numPages)continue;if(added)doc.addPage();const pg=await pdf.getPage(p);const{canvas,w,h}=await renderPage(pg,1.5);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/w,ph/h);doc.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',(pw-w*r)/2,(ph-h*r)/2,w*r,h*r);added=true;updateOverlay(20+70*pages.indexOf(p)/pages.length,'Page '+p);await delay(50)}return{type:'blob',blob:doc.output('blob'),fileName:'extrait.pdf',info:pages.length+' page(s)'}}
async function cvRotatePdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF({orientation:'landscape'});for(let i=1;i<=pdf.numPages;i++){if(i>1)doc.addPage();const pg=await pdf.getPage(i);const{canvas,w,h}=await renderPage(pg,1.5);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/h,ph/w);doc.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',(pw-h*r)/2,(ph-w*r)/2,h*r,w*r);updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'blob',blob:doc.output('blob'),fileName:'pivote.pdf',info:pdf.numPages+' page(s) pivotee(s)'}}
async function cvNumberPages(s){const{jsPDF}=window.jspdf;animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF();for(let i=1;i<=pdf.numPages;i++){if(i>1)doc.addPage();const pg=await pdf.getPage(i);const{canvas,w,h}=await renderPage(pg,1.5);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/w,ph/h);doc.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',(pw-w*r)/2,(ph-h*r)/2,w*r,h*r);doc.setFontSize(10);doc.setTextColor(150);doc.text(i+' / '+pdf.numPages,pw/2,ph-15,{align:'center'});updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'blob',blob:doc.output('blob'),fileName:'numerote.pdf',info:pdf.numPages+' page(s) numerotee(s)'}}
async function cvHtmlToPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const html=document.getElementById('textInput').value;const d=new DOMParser().parseFromString(html,'text/html');const txt=d.body?d.body.textContent:html;const doc=new jsPDF();doc.setFont('helvetica');doc.setFontSize(11);const lines=doc.splitTextToSize(txt,170);const ph=doc.internal.pageSize.getHeight()-40;let y=20,i=0;while(i<lines.length){if(y+6>ph+20){doc.addPage();y=20}doc.text(lines[i],20,y);y+=6;i++}return{type:'blob',blob:doc.output('blob'),fileName:'html.pdf',info:lines.length+' ligne(s)'}}
async function cvWatermarkPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const wm=document.getElementById('watermarkInput').value||'CONFIDENTIEL';const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF();for(let i=1;i<=pdf.numPages;i++){if(i>1)doc.addPage();const pg=await pdf.getPage(i);const{canvas,w,h}=await renderPage(pg,1.5);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/w,ph/h);doc.addImage(canvas.toDataURL('image/jpeg',.9),'JPEG',(pw-w*r)/2,(ph-h*r)/2,w*r,h*r);doc.saveGraphicsState();doc.setGState(new doc.GState({opacity:.1}));doc.setFontSize(44);doc.setTextColor(180,0,0);doc.text(wm,pw/2,ph/2,{angle:Math.atan2(ph,pw),align:'center'});doc.restoreGraphicsState();updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}return{type:'blob',blob:doc.output('blob'),fileName:'filigrane.pdf',info:pdf.numPages+' page(s), "'+wm+'"'}}
async function cvExtractImages(s){animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const imgs=[];for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i);const ops=pg.getOperatorList();ops.fnArray.forEach((fn,idx)=>{if(fn==='paintJpegXObject'||fn==='paintImageXObject'){try{const obj=pg.objs.get(ops.argsArray[idx][0]);if(obj&&obj.bitmap){const c=document.createElement('canvas');c.width=obj.width;c.height=obj.height;c.getContext('2d').putImageData(obj.bitmap,0,0);imgs.push(c.toDataURL('image/png'))}}catch(e){}}});updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(80)}if(!imgs.length){for(let i=1;i<=pdf.numPages;i++){const{canvas}=await renderPage(pdf.getPage(i),1.5);imgs.push(canvas.toDataURL('image/png'));await delay(40)}}return{type:'images',images:imgs,fileName:uploadedFiles[0].name.replace('.pdf',''),info:imgs.length+' image(s) extraite(s)'}}
async function cvCompressPdf(s){const{jsPDF}=window.jspdf;animSteps(s,350);const ab=await uploadedFiles[0].arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const doc=new jsPDF();const origSize=uploadedFiles[0].size;for(let i=1;i<=pdf.numPages;i++){if(i>1)doc.addPage();const pg=await pdf.getPage(i);const{canvas,w,h}=await renderPage(pg,1);const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight();const r=Math.min(pw/w,ph/h);doc.addImage(canvas.toDataURL('image/jpeg',.45),'JPEG',(pw-w*r)/2,(ph-h*r)/2,w*r,h*r);updateOverlay(10+85*i/pdf.numPages,'Page '+i);await delay(50)}const blob=doc.output('blob');return{type:'blob',blob:blob,fileName:'compresse.pdf',info:pdf.numPages+' page(s), -'+Math.round((1-blob.size/origSize)*100)+'%'}}

function showResult(r){document.getElementById('resultArea').style.display='block';document.getElementById('resultInfo').textContent=r.info;const tr=document.getElementById('textResult'),btn=document.getElementById('downloadBtn');
  if(r.type==='text'){tr.style.display='block';document.getElementById('extractedText').textContent=r.text.substring(0,5000)+(r.text.length>5000?'\n\n...':'');btn.innerHTML='<i class="fas fa-download"></i> Telecharger'}
  else if(r.type==='images'){tr.style.display='block';const c=document.getElementById('extractedText');c.textContent='';const w=document.createElement('div');w.style.cssText='display:flex;flex-wrap:wrap;gap:8px';r.images.forEach((img,i)=>{const d=document.createElement('div');d.style.textAlign='center';d.innerHTML='<img src="'+img+'" style="max-width:150px;border-radius:6px;border:1px solid var(--border)"><p style="font-size:10px;color:var(--muted);margin-top:3px">'+(i+1)+'</p>';w.appendChild(d)});c.appendChild(w);btn.innerHTML='<i class="fas fa-download"></i> Telecharger'}
  else{tr.style.display='none';btn.innerHTML='<i class="fas fa-download"></i> Telecharger le PDF'}
  document.getElementById('convertBtn').disabled=false;toast('Conversion terminee !','success')}
function downloadResult(){if(!conversionResult)return;const r=conversionResult;if(r.type==='text')dlBlob(new Blob([r.text],{type:'text/plain;charset=utf-8'}),r.fileName);else if(r.type==='images')r.images.forEach((img,i)=>{const a=document.createElement('a');a.href=img;a.download=r.fileName+'_page_'+(i+1)+'.png';a.click()});else dlBlob(r.blob,r.fileName)}
function dlBlob(b,n){const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=n;a.click();URL.revokeObjectURL(u)}

let pricingMode='monthly';
const PLANS=[
  {id:'free',name:'Gratuit',badge:'Gratuit',bc:'pc-badge-free',pm:0,py:0,d:'Pour decouvrir',fm:['3 outils gratuits','3 conversions / 48h','Fichiers max 5 Mo'],btn:'Commencer',btnC:'btn-pc-outline pc-btn'},
  {id:'pro',name:'Pro',badge:'Pro',bc:'pc-badge-pro',pm:0.99,py:0.59,d:'Particuliers',fm:['Conversions illimitees','Fichiers max 50 Mo','18 outils','Historique'],btn:"S'abonner",btnC:'btn-modal-primary pc-btn',pop:true,sk:'pro'},
  {id:'biz',name:'Business',badge:'Business',bc:'pc-badge-biz',pm:9.99,py:5.99,d:'Equipes',fm:['Tout Pro inclus','5 comptes','Support prioritaire'],btn:"S'abonner",btnC:'btn-pc-outline pc-btn',sk:'biz'},
  {id:'ent',name:'Entreprise',badge:'Entreprise',bc:'pc-badge-ent',pm:99.99,py:59.99,d:'Sur mesure',fm:['Tout Business inclus','Comptes illimites','API d\'acces'],btn:'Nous contacter',btnC:'btn-pc-outline pc-btn',sk:'ent'}
];
function setPricing(m){pricingMode=m;document.getElementById('ptMonthly').classList.toggle('active',m==='monthly');document.getElementById('ptYearly').classList.toggle('active',m==='yearly');buildPricing()}
function buildPricing(){const g=document.getElementById('pricingGrid');g.innerHTML='';PLANS.forEach((p,i)=>{const price=pricingMode==='monthly'?p.pm:p.py;const card=document.createElement('div');card.className='pricing-card reveal'+(p.pop?' popular':'');card.style.transitionDelay=(i*0.05)+'s';card.innerHTML=`${p.pop?'<div class="popular-tag">LE PLUS POPULAIRE</div>':''}<div class="${p.bc}">${p.badge}</div><div class="pc-price"><span class="pc-amount">${price===0?'Gratuit':price.toFixed(2).replace('.',',')}</span>${price>0?'<span class="pc-currency">&euro;</span>':''}</div><div class="pc-period">${price===0?'Pour toujours':'/mois'}</div><ul class="pc-features">${p.fm.map(f=>'<li><i class="fas fa-check"></i> '+f+'</li>').join('')}</ul><button class="${p.btnC}" onclick="${p.id==='free'?'handleFreePlan()':p.id==='ent'?'toast(\'Contactez-nous\',\'info\')':'handleProPlan(\''+p.id+'\')'}">${p.btn}</button>`;g.appendChild(card)});setTimeout(initReveal,50)}

function refreshDashboard(){const u=getUser();if(!u)return;refreshCycle(u);document.getElementById('dashUsername').textContent=u.name;document.getElementById('dashUsed').textContent=u.isPro?'Illimite':(u.cycleUsed||0);document.getElementById('dashLimit').textContent=u.isPro?'':'sur '+FREE_LIMIT;document.getElementById('dashTotal').textContent=u.totalConversions||0;const badge=document.getElementById('dashBadge'),upBtn=document.getElementById('dashUpgradeBtn');if(u.isPro){badge.className='badge-pro';badge.innerHTML='<i class="fas fa-crown"></i> Pro';upBtn.style.display='none'}else{badge.className='badge-free';badge.textContent='Gratuit';upBtn.style.display='inline-flex'}const circ=2*Math.PI*34;if(!u.isPro){const rem=getTimeLeft(u),frac=rem/CYCLE_MS;const tc=document.getElementById('timerCircle');tc.style.strokeDasharray=circ;tc.style.strokeDashoffset=circ*(1-frac);tc.style.stroke='#2B7BF5';document.getElementById('timerText').textContent=fmtTime(rem)}else{document.getElementById('timerCircle').style.strokeDashoffset=0;document.getElementById('timerCircle').style.stroke='#10B981';document.getElementById('timerText').textContent='--'}const list=document.getElementById('historyList');if(!u.history||!u.history.length)list.innerHTML='<div class="table-empty"><i class="fas fa-inbox"></i><p>Aucune conversion</p></div>';else{const names={};Object.entries(TOOLS).forEach(([k,v])=>names[k]=v.t);list.innerHTML=u.history.slice(0,20).map(h=>'<div class="table-row"><span style="display:flex;align-items:center;gap:5px"><i class="fas fa-file" style="color:var(--muted);font-size:10px"></i>'+h.fileName+'</span><span style="color:var(--blue);font-size:11px">'+(names[h.tool]||h.tool)+'</span><span style="color:var(--muted);font-size:11px">'+new Date(h.date).toLocaleDateString('fr-FR')+'</span><span style="color:var(--green);font-size:11px"><i class="fas fa-check-circle"></i></span></div>').join('')}}
function clearHistory(){const u=getUser();if(!u)return;u.history=[];saveUser(u);refreshDashboard();toast('Efface','info')}

function processStripeCheckout(){const u=getUser();if(!u){openModal('login');return}if(u.isPro){toast('Deja abonne','info');return}const pk=STRIPE_PRICES[selectedPlan];if(!pk||STRIPE_PK==='VOTRE_CLE_PUBLIQUE_STRIPE'){const btn=document.getElementById('stripeCheckoutBtn');btn.disabled=true;btn.innerHTML='<i class="fas fa-exclamation-triangle"></i> Non configure';const h=document.getElementById('stripeHelp');h.style.display='block';h.innerHTML='<strong>Stripe requis :</strong><br>1. <a href="https://dashboard.stripe.com/register" target="_blank" style="color:var(--blue)">stripe.com</a><br>2. Liez votre compte bancaire<br>3. Creez 3 produits<br>4. Copiez les cles dans script.js';return}const btn=document.getElementById('stripeCheckoutBtn');btn.disabled=true;btn.innerHTML='<i class="fas fa-spinner fa-spin"></i> Ouverture...';try{if(!stripeInstance)stripeInstance=Stripe(STRIPE_PK);stripeInstance.redirectToCheckout({lineItems:[{price:pk,quantity:1}],mode:'subscription',successUrl:location.origin+location.pathname+'?upgrade=success&uid='+u.id+'&plan='+selectedPlan,cancelUrl:location.origin+location.pathname+'?upgrade=cancel',customerEmail:u.email,locale:'fr'}).then(r=>{if(r.error){toast(r.error.message,'error');btn.disabled=false;btn.innerHTML='<i class="fas fa-credit-card"></i> Payer avec Stripe'}})}catch(e){toast('Erreur','error');btn.disabled=false;btn.innerHTML='<i class="fas fa-credit-card"></i> Payer avec Stripe'}}
function checkStripeReturn(){const p=new URLSearchParams(location.search);const uid=p.get('uid'),s=p.get('upgrade'),plan=p.get('plan');if(s==='success'&&uid){const us=getUsers(),u=us[uid];if(u){u.isPro=true;saveUser(u);currentUser=u;updateNav();toast('Bienvenue dans le plan '+(plan||'Pro')+' !','success')}history.replaceState({},'',location.pathname)}else if(s==='cancel'){toast('Annule','info');history.replaceState({},'',location.pathname)}}
function handleFreePlan(){const u=getUser();if(!u)openModal('register');else navigate('tools')}
function handleProPlan(planId){selectedPlan=planId||'pro';const u=getUser();if(!u){openModal('register');toast('Creez un compte','info');return}if(u.isPro){toast('Deja abonne','info');return}const nm={pro:'Pro',biz:'Business',ent:'Entreprise'},ds={pro:'Illimite',biz:'Equipe',ent:'Sur mesure'},pr={pro:'0,99€',biz:'9,99€',ent:'99,99€'};document.getElementById('subPlanName').textContent='Plan '+nm[selectedPlan];document.getElementById('subPlanDesc').textContent=ds[selectedPlan];document.getElementById('subPlanPrice').innerHTML=pr[selectedPlan]+'<span>/mois</span>';document.getElementById('stripeHelp').style.display='none';const btn=document.getElementById('stripeCheckoutBtn');btn.disabled=false;btn.innerHTML='<i class="fas fa-credit-card"></i> Payer avec Stripe';openModal('subscribe')}

setInterval(()=>{const u=getUser();if(!u||u.isPro)return;const rem=getTimeLeft(u),circ=2*Math.PI*34;const tc=document.getElementById('timerCircle'),tt=document.getElementById('timerText');if(tc&&tt){tc.style.strokeDasharray=circ;tc.style.strokeDashoffset=circ*(1-rem/CYCLE_MS);tt.textContent=fmtTime(rem)}if(rem===0&&u.cycleUsed>0){refreshCycle(u);updateLimitUI();if(document.getElementById('page-dashboard').classList.contains('page-visible'))refreshDashboard();toast('Quota renouvele !','success')}},1000);
document.getElementById('textInput').addEventListener('input',function(){if(TOOLS[currentTool].tx)document.getElementById('convertBtn').disabled=!this.value.trim()});
window.addEventListener('scroll',()=>document.getElementById('header').classList.toggle('header-scrolled',window.scrollY>20));

document.addEventListener('DOMContentLoaded',()=>{currentUser=getUser();updateNav();buildDropdown();buildToolsGrid();buildVisBand();buildPricing();checkStripeReturn();initReveal();initCounters();typewriter(document.getElementById('heroTypewriter'),'Nous simplifions la gestion de vos PDF.',42)});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
